version: '3.1'

services:

  parishand_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "5000:3306"
    environment:
      MYSQL_DATABASE: parishand
      MYSQL_ROOT_PASSWORD: root